[2022-10-28T19:31:28.757+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: ENG_hourly_process_v1.get_hourly_demand scheduled__2022-10-28T11:05:00+00:00 [queued]>
[2022-10-28T19:31:28.865+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: ENG_hourly_process_v1.get_hourly_demand scheduled__2022-10-28T11:05:00+00:00 [queued]>
[2022-10-28T19:31:28.866+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2022-10-28T19:31:28.867+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 2
[2022-10-28T19:31:28.868+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2022-10-28T19:31:28.963+0000] {taskinstance.py:1383} INFO - Executing <Task(PythonOperator): get_hourly_demand> on 2022-10-28 11:05:00+00:00
[2022-10-28T19:31:29.039+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'ENG_hourly_process_v1', 'get_hourly_demand', 'scheduled__2022-10-28T11:05:00+00:00', '--job-id', '156', '--raw', '--subdir', 'DAGS_FOLDER/ENG_hourly_process_dag.py', '--cfg-path', '/tmp/tmpe9htrlr0']
[2022-10-28T19:31:29.043+0000] {standard_task_runner.py:83} INFO - Job 156: Subtask get_hourly_demand
[2022-10-28T19:31:29.023+0000] {standard_task_runner.py:55} INFO - Started process 496 to run task
[2022-10-28T19:31:29.413+0000] {task_command.py:376} INFO - Running <TaskInstance: ENG_hourly_process_v1.get_hourly_demand scheduled__2022-10-28T11:05:00+00:00 [running]> on host f011703e6eb5
[2022-10-28T19:31:32.014+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=colmo786@gmail.com
AIRFLOW_CTX_DAG_OWNER=energy
AIRFLOW_CTX_DAG_ID=ENG_hourly_process_v1
AIRFLOW_CTX_TASK_ID=get_hourly_demand
AIRFLOW_CTX_EXECUTION_DATE=2022-10-28T11:05:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-10-28T11:05:00+00:00
[2022-10-28T19:31:32.199+0000] {logging_mixin.py:120} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:297 AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
[2022-10-28T19:31:35.036+0000] {logging_mixin.py:120} INFO - INFO Module build_postgres_cnxn: DB Connection to host local_pgdb Ok
[2022-10-28T19:31:53.101+0000] {logging_mixin.py:120} INFO - ERROR api_request_to_pandas: Error requesting API: https://api.cammesa.com/demanda-svc/demanda/ObtieneDemandaYTemperaturaRegionByFecha?fecha=2022-10-28&id_region=1002
Traceback (most recent call last):   File "/usr/local/lib/python3.7/urllib/request.py", line 1350, in do_open     encode_chunked=req.has_header('Transfer-encoding'))   File "/usr/local/lib/python3.7/http/client.py", line 1281, in request     self._send_request(method, url, body, headers, encode_chunked)   File "/usr/local/lib/python3.7/http/client.py", line 1327, in _send_request     self.endheaders(body, encode_chunked=encode_chunked)   File "/usr/local/lib/python3.7/http/client.py", line 1276, in endheaders     self._send_output(message_body, encode_chunked=encode_chunked)   File "/usr/local/lib/python3.7/http/client.py", line 1036, in _send_output     self.send(msg)   File "/usr/local/lib/python3.7/http/client.py", line 976, in send     self.connect()   File "/usr/local/lib/python3.7/http/client.py", line 1443, in connect     super().connect()   File "/usr/local/lib/python3.7/http/client.py", line 948, in connect     (self.host,self.port), self.timeout, self.source_address)   File "/usr/local/lib/python3.7/socket.py", line 707, in create_connection     for res in getaddrinfo(host, port, 0, SOCK_STREAM):   File "/usr/local/lib/python3.7/socket.py", line 752, in getaddrinfo     for res in _socket.getaddrinfo(host, port, family, type, proto, flags): socket.gaierror: [Errno -3] Temporary failure in name resolution  During handling of the above exception, another exception occurred:  Traceback (most recent call last):   File "/opt/***/dags/energy.py", line 111, in _url_request_to_pandas     response = urllib.request.urlopen(_request)   File "/usr/local/lib/python3.7/urllib/request.py", line 222, in urlopen     return opener.open(url, data, timeout)   File "/usr/local/lib/python3.7/urllib/request.py", line 525, in open     response = self._open(req, data)   File "/usr/local/lib/python3.7/urllib/request.py", line 543, in _open     '_open', req)   File "/usr/local/lib/python3.7/urllib/request.py", line 503, in _call_chain     result = func(*args)   File "/usr/local/lib/python3.7/urllib/request.py", line 1393, in https_open     context=self._context, check_hostname=self._check_hostname)   File "/usr/local/lib/python3.7/urllib/request.py", line 1352, in do_open     raise URLError(err) urllib.error.URLError: <urlopen error [Errno -3] Temporary failure in name resolution>
[2022-10-28T19:31:53.111+0000] {logging_mixin.py:120} INFO - INFO get_hourly_demand execution:  2022-10-28T11:05:00+00:00
[2022-10-28T19:31:53.112+0000] {taskinstance.py:1851} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 193, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/ENG_hourly_process_dag.py", line 52, in get_hourly_demand
    raise ValueError()
ValueError
[2022-10-28T19:32:01.558+0000] {taskinstance.py:1406} INFO - Marking task as UP_FOR_RETRY. dag_id=ENG_hourly_process_v1, task_id=get_hourly_demand, execution_date=20221028T110500, start_date=20221028T193128, end_date=20221028T193201
[2022-10-28T19:32:01.915+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 156 for task get_hourly_demand (; 496)
[2022-10-28T19:32:02.027+0000] {local_task_job.py:164} INFO - Task exited with return code 1
[2022-10-28T19:32:02.211+0000] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
