[2022-10-28T22:32:38.217+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: ENG_hourly_process_v1.calculate_hourly_demand_forecast scheduled__2022-10-26T14:05:00+00:00 [queued]>
[2022-10-28T22:32:38.288+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: ENG_hourly_process_v1.calculate_hourly_demand_forecast scheduled__2022-10-26T14:05:00+00:00 [queued]>
[2022-10-28T22:32:38.298+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2022-10-28T22:32:38.299+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 2
[2022-10-28T22:32:38.300+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2022-10-28T22:32:38.405+0000] {taskinstance.py:1383} INFO - Executing <Task(PythonOperator): calculate_hourly_demand_forecast> on 2022-10-26 14:05:00+00:00
[2022-10-28T22:32:38.442+0000] {standard_task_runner.py:55} INFO - Started process 948 to run task
[2022-10-28T22:32:38.492+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'ENG_hourly_process_v1', 'calculate_hourly_demand_forecast', 'scheduled__2022-10-26T14:05:00+00:00', '--job-id', '14', '--raw', '--subdir', 'DAGS_FOLDER/ENG_hourly_process_dag.py', '--cfg-path', '/tmp/tmpvqm7hi02']
[2022-10-28T22:32:38.496+0000] {standard_task_runner.py:83} INFO - Job 14: Subtask calculate_hourly_demand_forecast
[2022-10-28T22:32:38.972+0000] {task_command.py:376} INFO - Running <TaskInstance: ENG_hourly_process_v1.calculate_hourly_demand_forecast scheduled__2022-10-26T14:05:00+00:00 [running]> on host 74ce152bc4b9
[2022-10-28T22:32:39.483+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=colmo786@gmail.com
AIRFLOW_CTX_DAG_OWNER=energy
AIRFLOW_CTX_DAG_ID=ENG_hourly_process_v1
AIRFLOW_CTX_TASK_ID=calculate_hourly_demand_forecast
AIRFLOW_CTX_EXECUTION_DATE=2022-10-26T14:05:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-10-26T14:05:00+00:00
[2022-10-28T22:32:39.518+0000] {logging_mixin.py:120} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:297 AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
[2022-10-28T22:32:39.519+0000] {logging_mixin.py:120} INFO - INFO calculate_hourly_demand_forecast execution init:  2022-10-26T14:05:00+00:00
[2022-10-28T22:32:39.519+0000] {logging_mixin.py:120} INFO - WORKDIR: /opt/***
[2022-10-28T22:32:39.543+0000] {logging_mixin.py:120} INFO - INFO Module build_postgres_cnxn: DB Connection to host local_pgdb Ok
[2022-10-28T22:32:39.555+0000] {logging_mixin.py:120} INFO - INFO pg_select_to_pandas: query executed Ok. Number of records returned: 1
[2022-10-28T22:32:39.562+0000] {logging_mixin.py:120} INFO - INFO pg_select_to_pandas: query executed Ok. Number of records returned: 48
[2022-10-28T22:34:48.580+0000] {local_task_job.py:228} WARNING - State of this instance has been externally set to queued. Terminating instance.
[2022-10-28T22:34:48.782+0000] {process_utils.py:133} INFO - Sending Signals.SIGTERM to group 948. PIDs of all processes in the group: [948]
[2022-10-28T22:34:48.783+0000] {process_utils.py:84} INFO - Sending the signal Signals.SIGTERM to group 948
[2022-10-28T22:34:48.842+0000] {taskinstance.py:1562} ERROR - Received SIGTERM. Terminating subprocesses.
[2022-10-28T22:34:49.404+0000] {taskinstance.py:1851} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 193, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/ENG_hourly_process_dag.py", line 63, in calculate_hourly_demand_forecast
    , port=port, n_lookback=48, n_forecast=24, verbose=True)
  File "/opt/airflow/dags/energy.py", line 237, in _calculate_hourly_demand_forecast
    Y_ = model.predict(X_).reshape(-1, 1)
  File "/home/airflow/.local/lib/python3.7/site-packages/keras/utils/traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/tmp/__autograph_generated_filewlbb378v.py", line 15, in tf__predict_function
    retval_ = ag__.converted_call(ag__.ld(step_function), (ag__.ld(self), ag__.ld(iterator)), None, fscope)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1564, in signal_handler
    raise AirflowException("Task received SIGTERM signal")
airflow.exceptions.AirflowException: in user code:

    File "/home/***/.local/lib/python3.7/site-packages/keras/engine/training.py", line 2041, in predict_function  *
        return step_function(self, iterator)
    File "/home/***/.local/lib/python3.7/site-packages/keras/engine/training.py", line 2027, in step_function  **
        outputs = model.distribute_strategy.run(run_step, args=(data,))
    File "/home/***/.local/lib/python3.7/site-packages/keras/engine/training.py", line 2015, in run_step  **
        outputs = model.predict_step(data)
    File "/home/***/.local/lib/python3.7/site-packages/keras/engine/training.py", line 1983, in predict_step
        return self(x, training=False)
    File "/home/***/.local/lib/python3.7/site-packages/keras/utils/traceback_utils.py", line 70, in error_handler
        raise e.with_traceback(filtered_tb) from None
    File "/home/***/.local/lib/python3.7/site-packages/***/models/taskinstance.py", line 1564, in signal_handler
        raise AirflowException("Task received SIGTERM signal")

    AirflowException: Exception encountered when calling layer "lstm_1" "                 f"(type LSTM).
    
    Task received SIGTERM signal
    
    Call arguments received by layer "lstm_1" "                 f"(type LSTM):
      • inputs=tf.Tensor(shape=(None, 48, 50), dtype=float32)
      • mask=None
      • training=False
      • initial_state=None

[2022-10-28T22:34:49.550+0000] {taskinstance.py:1406} INFO - Marking task as FAILED. dag_id=ENG_hourly_process_v1, task_id=calculate_hourly_demand_forecast, execution_date=20221026T140500, start_date=20221028T223238, end_date=20221028T223449
[2022-10-28T22:34:53.584+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 14 for task calculate_hourly_demand_forecast (in user code:

    File "/home/***/.local/lib/python3.7/site-packages/keras/engine/training.py", line 2041, in predict_function  *
        return step_function(self, iterator)
    File "/home/***/.local/lib/python3.7/site-packages/keras/engine/training.py", line 2027, in step_function  **
        outputs = model.distribute_strategy.run(run_step, args=(data,))
    File "/home/***/.local/lib/python3.7/site-packages/keras/engine/training.py", line 2015, in run_step  **
        outputs = model.predict_step(data)
    File "/home/***/.local/lib/python3.7/site-packages/keras/engine/training.py", line 1983, in predict_step
        return self(x, training=False)
    File "/home/***/.local/lib/python3.7/site-packages/keras/utils/traceback_utils.py", line 70, in error_handler
        raise e.with_traceback(filtered_tb) from None
    File "/home/***/.local/lib/python3.7/site-packages/***/models/taskinstance.py", line 1564, in signal_handler
        raise AirflowException("Task received SIGTERM signal")

    AirflowException: Exception encountered when calling layer "lstm_1" "                 f"(type LSTM).
    
    Task received SIGTERM signal
    
    Call arguments received by layer "lstm_1" "                 f"(type LSTM):
      • inputs=tf.Tensor(shape=(None, 48, 50), dtype=float32)
      • mask=None
      • training=False
      • initial_state=None
; 948)
[2022-10-28T22:34:55.204+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=948, status='terminated', exitcode=1, started='22:32:38') (948) terminated with exit code 1
[2022-10-29T00:35:53.171+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: ENG_hourly_process_v1.calculate_hourly_demand_forecast scheduled__2022-10-26T14:05:00+00:00 [queued]>
[2022-10-29T00:35:53.276+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: ENG_hourly_process_v1.calculate_hourly_demand_forecast scheduled__2022-10-26T14:05:00+00:00 [queued]>
[2022-10-29T00:35:53.294+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2022-10-29T00:35:53.294+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 2
[2022-10-29T00:35:53.294+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2022-10-29T00:35:53.432+0000] {taskinstance.py:1383} INFO - Executing <Task(PythonOperator): calculate_hourly_demand_forecast> on 2022-10-26 14:05:00+00:00
[2022-10-29T00:35:53.536+0000] {standard_task_runner.py:55} INFO - Started process 819 to run task
[2022-10-29T00:35:53.542+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'ENG_hourly_process_v1', 'calculate_hourly_demand_forecast', 'scheduled__2022-10-26T14:05:00+00:00', '--job-id', '33', '--raw', '--subdir', 'DAGS_FOLDER/ENG_hourly_process_dag.py', '--cfg-path', '/tmp/tmpg72gwivu']
[2022-10-29T00:35:53.545+0000] {standard_task_runner.py:83} INFO - Job 33: Subtask calculate_hourly_demand_forecast
[2022-10-29T00:35:53.999+0000] {task_command.py:376} INFO - Running <TaskInstance: ENG_hourly_process_v1.calculate_hourly_demand_forecast scheduled__2022-10-26T14:05:00+00:00 [running]> on host 6800cd8e39a3
[2022-10-29T00:35:54.705+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=colmo786@gmail.com
AIRFLOW_CTX_DAG_OWNER=energy
AIRFLOW_CTX_DAG_ID=ENG_hourly_process_v1
AIRFLOW_CTX_TASK_ID=calculate_hourly_demand_forecast
AIRFLOW_CTX_EXECUTION_DATE=2022-10-26T14:05:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-10-26T14:05:00+00:00
[2022-10-29T00:35:54.845+0000] {logging_mixin.py:120} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:297 AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
[2022-10-29T00:35:54.845+0000] {logging_mixin.py:120} INFO - INFO calculate_hourly_demand_forecast execution init:  2022-10-26T14:05:00+00:00
[2022-10-29T00:35:54.846+0000] {logging_mixin.py:120} INFO - WORKDIR: /opt/***
[2022-10-29T00:35:54.928+0000] {logging_mixin.py:120} INFO - INFO Module build_postgres_cnxn: DB Connection to host local_pgdb Ok
[2022-10-29T00:35:54.935+0000] {logging_mixin.py:120} INFO - INFO pg_select_to_pandas: query executed Ok. Number of records returned: 1
[2022-10-29T00:35:54.979+0000] {logging_mixin.py:120} INFO - INFO pg_select_to_pandas: query executed Ok. Number of records returned: 48
[2022-10-29T00:36:20.178+0000] {logging_mixin.py:120} INFO - 1/1 [==============================] - ETA: 0s
[2022-10-29T00:36:20.178+0000] {logging_mixin.py:120} INFO - 1/1 [==============================] - 13s 13s/step
[2022-10-29T00:36:20.261+0000] {logging_mixin.py:120} INFO - INFO _calculate_hourly_demand_forecast: forecast calculated for next 24 hours. Since: 2022-10-27 00:00
[2022-10-29T00:36:28.587+0000] {logging_mixin.py:120} INFO - INFO _calculate_hourly_demand_forecast - 24 records were upserted. Table cammesa_db.hourly_demand_forecast.
[2022-10-29T00:36:28.591+0000] {python.py:177} INFO - Done. Returned value was: None
[2022-10-29T00:36:28.615+0000] {taskinstance.py:1406} INFO - Marking task as SUCCESS. dag_id=ENG_hourly_process_v1, task_id=calculate_hourly_demand_forecast, execution_date=20221026T140500, start_date=20221029T003553, end_date=20221029T003628
[2022-10-29T00:36:29.020+0000] {local_task_job.py:164} INFO - Task exited with return code 0
[2022-10-29T00:36:29.148+0000] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
