[2022-10-28T22:32:38.267+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: ENG_hourly_process_v1.calculate_hourly_demand_forecast scheduled__2022-10-26T04:05:00+00:00 [queued]>
[2022-10-28T22:32:38.351+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: ENG_hourly_process_v1.calculate_hourly_demand_forecast scheduled__2022-10-26T04:05:00+00:00 [queued]>
[2022-10-28T22:32:38.352+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2022-10-28T22:32:38.352+0000] {taskinstance.py:1363} INFO - Starting attempt 2 of 2
[2022-10-28T22:32:38.353+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2022-10-28T22:32:38.423+0000] {taskinstance.py:1383} INFO - Executing <Task(PythonOperator): calculate_hourly_demand_forecast> on 2022-10-26 04:05:00+00:00
[2022-10-28T22:32:38.448+0000] {standard_task_runner.py:55} INFO - Started process 949 to run task
[2022-10-28T22:32:38.477+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'ENG_hourly_process_v1', 'calculate_hourly_demand_forecast', 'scheduled__2022-10-26T04:05:00+00:00', '--job-id', '12', '--raw', '--subdir', 'DAGS_FOLDER/ENG_hourly_process_dag.py', '--cfg-path', '/tmp/tmp8x6j0al3']
[2022-10-28T22:32:38.482+0000] {standard_task_runner.py:83} INFO - Job 12: Subtask calculate_hourly_demand_forecast
[2022-10-28T22:32:38.982+0000] {task_command.py:376} INFO - Running <TaskInstance: ENG_hourly_process_v1.calculate_hourly_demand_forecast scheduled__2022-10-26T04:05:00+00:00 [running]> on host 74ce152bc4b9
[2022-10-28T22:32:39.411+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=colmo786@gmail.com
AIRFLOW_CTX_DAG_OWNER=energy
AIRFLOW_CTX_DAG_ID=ENG_hourly_process_v1
AIRFLOW_CTX_TASK_ID=calculate_hourly_demand_forecast
AIRFLOW_CTX_EXECUTION_DATE=2022-10-26T04:05:00+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-10-26T04:05:00+00:00
[2022-10-28T22:32:39.446+0000] {logging_mixin.py:120} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:297 AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
[2022-10-28T22:32:39.454+0000] {logging_mixin.py:120} INFO - INFO calculate_hourly_demand_forecast execution init:  2022-10-26T04:05:00+00:00
[2022-10-28T22:32:39.454+0000] {logging_mixin.py:120} INFO - WORKDIR: /opt/***
[2022-10-28T22:32:39.477+0000] {logging_mixin.py:120} INFO - INFO Module build_postgres_cnxn: DB Connection to host local_pgdb Ok
[2022-10-28T22:32:39.498+0000] {logging_mixin.py:120} INFO - INFO pg_select_to_pandas: query executed Ok. Number of records returned: 1
[2022-10-28T22:32:39.505+0000] {logging_mixin.py:120} INFO - INFO pg_select_to_pandas: query executed Ok. Number of records returned: 48
[2022-10-28T22:34:49.026+0000] {local_task_job.py:228} WARNING - State of this instance has been externally set to queued. Terminating instance.
[2022-10-28T22:34:49.136+0000] {process_utils.py:133} INFO - Sending Signals.SIGTERM to group 949. PIDs of all processes in the group: [949]
[2022-10-28T22:34:49.137+0000] {process_utils.py:84} INFO - Sending the signal Signals.SIGTERM to group 949
[2022-10-28T22:34:58.077+0000] {taskinstance.py:1562} ERROR - Received SIGTERM. Terminating subprocesses.
[2022-10-28T22:34:58.122+0000] {taskinstance.py:1851} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 193, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/ENG_hourly_process_dag.py", line 63, in calculate_hourly_demand_forecast
    , port=port, n_lookback=48, n_forecast=24, verbose=True)
  File "/opt/airflow/dags/energy.py", line 237, in _calculate_hourly_demand_forecast
    Y_ = model.predict(X_).reshape(-1, 1)
  File "/home/airflow/.local/lib/python3.7/site-packages/keras/utils/traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1564, in signal_handler
    raise AirflowException("Task received SIGTERM signal")
airflow.exceptions.AirflowException: Task received SIGTERM signal
[2022-10-28T22:34:58.140+0000] {taskinstance.py:1406} INFO - Marking task as FAILED. dag_id=ENG_hourly_process_v1, task_id=calculate_hourly_demand_forecast, execution_date=20221026T040500, start_date=20221028T223238, end_date=20221028T223458
[2022-10-28T22:34:58.213+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 12 for task calculate_hourly_demand_forecast (Task received SIGTERM signal; 949)
[2022-10-28T22:34:58.633+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=949, status='terminated', exitcode=1, started='22:32:38') (949) terminated with exit code 1
